export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './breakdown.service';
import { BreakdownService } from './breakdown.service';
export * from './breakdown.serviceInterface';
export * from './breakdownTypes.service';
import { BreakdownTypesService } from './breakdownTypes.service';
export * from './breakdownTypes.serviceInterface';
export * from './machine.service';
import { MachineService } from './machine.service';
export * from './machine.serviceInterface';
export * from './sparePart.service';
import { SparePartService } from './sparePart.service';
export * from './sparePart.serviceInterface';
export const APIS = [AuthenticationService, BreakdownService, BreakdownTypesService, MachineService, SparePartService];
