/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { JwtAuthRequest } from '../model/models';
import { JwtAuthResponse } from '../model/models';
import { RegisterRequest } from '../model/models';
import { UserProfileResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get current user profile
     * Retrieves profile information for the currently authenticated user. Requires a valid JWT Bearer token.
     */
    getCurrentUser(extraHttpRequestParams?: any): Observable<UserProfileResponse>;

    /**
     * Authenticate a user (login)
     * Verifies user credentials and returns a JWT token if they are valid.
     * @param jwtAuthRequest 
     */
    login(jwtAuthRequest: JwtAuthRequest, extraHttpRequestParams?: any): Observable<JwtAuthResponse>;

    /**
     * Register a new user
     * Creates a new user account and returns a JWT token upon successful registration.
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<JwtAuthResponse>;

}
