/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MachineCreateRequest } from '../model/models';
import { MachineDetailsResponse } from '../model/models';
import { MachineUpdateRequest } from '../model/models';
import { PageMachineDetailsResponse } from '../model/models';
import { Pageable } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MachineServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param machineCreateRequest 
     */
    createMachine(machineCreateRequest: MachineCreateRequest, extraHttpRequestParams?: any): Observable<MachineDetailsResponse>;

    /**
     * 
     * 
     * @param id 
     */
    deleteMachine(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param pageable 
     */
    getAllMachines(pageable: Pageable, extraHttpRequestParams?: any): Observable<PageMachineDetailsResponse>;

    /**
     * 
     * 
     */
    getAllMachinesAsList(extraHttpRequestParams?: any): Observable<Array<MachineDetailsResponse>>;

    /**
     * 
     * 
     * @param id 
     */
    getMachineById(id: number, extraHttpRequestParams?: any): Observable<MachineDetailsResponse>;

    /**
     * 
     * 
     * @param id 
     * @param machineUpdateRequest 
     */
    updateMachine(id: number, machineUpdateRequest: MachineUpdateRequest, extraHttpRequestParams?: any): Observable<MachineDetailsResponse>;

}
