/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageSparePartResponse } from '../model/models';
import { Pageable } from '../model/models';
import { SparePartCreateRequest } from '../model/models';
import { SparePartResponse } from '../model/models';
import { SparePartUpdateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SparePartServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param sparePartCreateRequest 
     */
    createSparePart(sparePartCreateRequest: SparePartCreateRequest, extraHttpRequestParams?: any): Observable<SparePartResponse>;

    /**
     * 
     * 
     * @param id 
     */
    deleteSparePart(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param pageable 
     */
    getAllSpareParts(pageable: Pageable, extraHttpRequestParams?: any): Observable<PageSparePartResponse>;

    /**
     * 
     * 
     * @param id 
     */
    getSparePartById(id: number, extraHttpRequestParams?: any): Observable<SparePartResponse>;

    /**
     * 
     * 
     * @param id 
     * @param sparePartUpdateRequest 
     */
    updateSparePart(id: number, sparePartUpdateRequest: SparePartUpdateRequest, extraHttpRequestParams?: any): Observable<SparePartResponse>;

}
