/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A response object for a part used in a breakdown
 */
export interface BreakdownUsedPartResponse { 
    id?: number;
    sparePartId?: number;
    sparePartName?: string;
    quantity?: number;
    pricePerUnit?: number;
}

