/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data required to create a new breakdown report
 */
export interface BreakdownCreateRequest { 
    description?: string;
    machineId?: number;
    type?: BreakdownCreateRequest.TypeEnum;
}
export namespace BreakdownCreateRequest {
    export const TypeEnum = {
        MECHANICAL: 'MECHANICAL',
        AUTOMATICAL: 'AUTOMATICAL',
        PARAMETERS: 'PARAMETERS'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


