/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A detailed response object with machine data
 */
export interface MachineDetailsResponse { 
    id?: number;
    code?: string;
    fullName?: string;
    serialNumber?: string;
    manufacturer?: string;
    productionDate?: string;
    description?: string;
}

