/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data required to create a new machine
 */
export interface MachineCreateRequest { 
    code?: string;
    fullName?: string;
    serialNumber?: string;
    manufacturer?: string;
    productionDate?: string;
    description?: string;
}

