/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BreakdownUsedPartResponse } from './breakdownUsedPartResponse';
import { MachineSummaryResponse } from './machineSummaryResponse';


export interface Response { 
    id?: number;
    description?: string;
    reportedAt?: string;
    startedAt?: string;
    finishedAt?: string;
    opened?: boolean;
    specialistComment?: string;
    type?: Response.TypeEnum;
    totalCost?: number;
    machine?: MachineSummaryResponse;
    usedParts?: Array<BreakdownUsedPartResponse>;
}
export namespace Response {
    export const TypeEnum = {
        MECHANICAL: 'MECHANICAL',
        AUTOMATICAL: 'AUTOMATICAL',
        PARAMETERS: 'PARAMETERS'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


