/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileDto } from './userProfileDto';


export interface UserProfileResponse { 
    status?: string;
    message?: string;
    data?: UserProfileDto;
}

